import type { InstanceName } from "../../kernel/instance-name";

// Paths are relative to the workspace root and always use "/" (ADR-0014).
export interface InstancePaths {
  readonly root: string;
  readonly profile: string;
  readonly metadata: string;
  readonly updateSets: string;
  readonly operational: string;
  readonly localState: string;
  readonly remoteBranch: string;
}

export function instancePaths(name: InstanceName): InstancePaths {
  const root = `instances/${name}`;
  return {
    root,
    profile: `${root}/instance.yaml`,
    metadata: `${root}/metadata`,
    updateSets: `${root}/update-sets`,
    operational: `${root}/operational`,
    localState: `.snagentic/${name}`,
    remoteBranch: `servicenow-remote/${name}`,
  };
}

export const GITIGNORE = [
  "# Generated by snagentic (ADR-0014).",
  "# Local state: sync state, indexes, locks and caches.",
  ".snagentic/",
  "# Never commit secrets.",
  ".env",
  ".env.*",
  "*.pem",
  "*.key",
  "",
].join("\n");
