import type { InstanceName } from "../../kernel/instance-name";

// Paths are relative to the workspace root and always use "/" (ADR-0014).
export interface InstancePaths {
  readonly root: string;
  readonly profile: string;
  readonly metadata: string;
  readonly updateSets: string;
  readonly operational: string;
  readonly localState: string;
  readonly remoteBranch: string;
}

export function instancePaths(name: InstanceName): InstancePaths {
  const root = `instances/${name}`;
  return {
    root,
    profile: `${root}/instance.yaml`,
    metadata: `${root}/metadata`,
    updateSets: `${root}/update-sets`,
    operational: `${root}/operational`,
    localState: `.snagentic/${name}`,
    remoteBranch: `servicenow-remote/${name}`,
  };
}

export const GITIGNORE = [
  "# Generated by snagentic (ADR-0014).",
  "# Local state: sync state, indexes, locks and caches.",
  ".snagentic/",
  "# Never commit secrets.",
  ".env",
  ".env.*",
  "*.pem",
  "*.key",
  "",
].join("\n");

// A path to a record's file as the mirror names it (relative to instances/<name>/metadata),
// given relative to it, to the workspace, or as an absolute path inside the workspace.
export function metadataPath(name: InstanceName, workspace: string, path: string): string {
  const metadata = `${instancePaths(name).metadata}/`;
  let relative = path.startsWith(`${workspace}/`) ? path.slice(workspace.length + 1) : path;
  relative = relative.startsWith(metadata) ? relative.slice(metadata.length) : relative;
  return relative.startsWith("./") ? relative.slice(2) : relative;
}
