import { SHELL_DENY } from "@snagentic/agent-packs";
import { z } from "zod";
import { isEditTool, isShellTool, toolCallOf } from "./host-payload";

// Agent host hooks (ADR-0011, layers 1 and 2), as an interface over the check and validate
// use cases: the host sends a JSON payload on stdin; the exit code and output tell it what to
// do. Written for Claude Code's settings, which Copilot CLI also reads (see host-payload.ts).
// Hooks help the agent; they never replace the push gate or CI, so any failure here lets the
// agent continue (exit 0) and says why on stderr.

export interface HookOutcome {
  readonly exitCode: number;
  readonly stdout: string;
  readonly stderr: string;
}

const Findings = z
  .array(
    z.object({
      ruleId: z.string(),
      severity: z.string(),
      path: z.string(),
      line: z.number().nullable(),
      message: z.string(),
      remediation: z.string(),
    }),
  )
  .catch([]);
type Finding = z.infer<typeof Findings>[number];
const Protected = z.array(z.object({ path: z.string(), reason: z.string() })).catch([]);
const Missing = z.array(z.string()).catch([]);
const NO_RECORD_FILE =
  "no such record file; deleting records is not supported: restore the file and set active to false";

// Runs a use case by name with an input, returning its output.
export type RunUseCase = (
  name: "check" | "validate",
  input: Record<string, unknown>,
) => Promise<Record<string, unknown>>;

export const CLAUDE_HOOK_EVENTS = ["pre-edit", "post-edit", "pre-shell", "stop"] as const;
export type ClaudeHookEvent = (typeof CLAUDE_HOOK_EVENTS)[number];

const OK: HookOutcome = { exitCode: 0, stdout: "", stderr: "" };

const field = (value: unknown, key: string): unknown =>
  value !== null && typeof value === "object" && key in value
    ? Object.fromEntries(Object.entries(value))[key]
    : undefined;

const findingsOf = (output: Record<string, unknown>): Finding[] =>
  Findings.parse(output["findings"]);

const line = (f: Finding) =>
  `${f.severity} ${f.ruleId} ${f.path}${f.line === null ? "" : `:${f.line}`}: ${f.message} Fix: ${f.remediation}`;

async function preEdit(paths: readonly string[], run: RunUseCase): Promise<HookOutcome> {
  const output = await run("check", { paths, edited: false });
  const blocked = Protected.parse(output["protected"]);
  if (blocked.length === 0) {
    return OK;
  }
  const reasons = blocked.map((p) => `${p.path}: ${p.reason}`);
  return {
    exitCode: 2,
    stdout: "",
    stderr: `snagentic: do not edit this file. ${reasons.join("; ")}`,
  };
}

async function postEdit(paths: readonly string[], run: RunUseCase): Promise<HookOutcome> {
  const output = await run("check", { paths, edited: true });
  const findings = findingsOf(output);
  const missing = Missing.parse(output["missing"]).map((path) => `${path}: ${NO_RECORD_FILE}`);
  const blocking = [...missing, ...findings.filter((f) => f.severity === "block").map(line)];
  if (blocking.length > 0) {
    return {
      exitCode: 2,
      stdout: "",
      stderr: `snagentic check found blocking problems:\n${blocking.join("\n")}`,
    };
  }
  if (findings.length === 0) {
    return OK;
  }
  const context = `snagentic check:\n${findings.map(line).join("\n")}`;
  return {
    exitCode: 0,
    // Claude Code reads the nested field; Copilot CLI reads the top-level one.
    stdout: JSON.stringify({
      hookSpecificOutput: { hookEventName: "PostToolUse", additionalContext: context },
      additionalContext: context,
    }),
    stderr: "",
  };
}

function preShell(command: string): HookOutcome {
  const denied = SHELL_DENY.find((rule) => rule.pattern.test(command));
  return denied === undefined
    ? OK
    : { exitCode: 2, stdout: "", stderr: `snagentic: command refused: ${denied.reason}.` };
}

// Before the agent ends its turn: no block finding may remain in what it changed. Asked once
// per stop (the host marks a repeated stop), so the agent can explain instead of looping.
async function stop(payload: unknown, run: RunUseCase): Promise<HookOutcome> {
  if (field(payload, "stop_hook_active") === true) {
    return OK;
  }
  const blocking = findingsOf(await run("validate", {})).filter((f) => f.severity === "block");
  if (blocking.length === 0) {
    return OK;
  }
  const reason = `validate still finds blocking problems in your changes; fix them, or tell the user why you cannot:\n${blocking.map(line).join("\n")}`;
  return { exitCode: 0, stdout: JSON.stringify({ decision: "block", reason }), stderr: "" };
}

export async function runClaudeHook(
  event: ClaudeHookEvent,
  payload: unknown,
  run: RunUseCase,
): Promise<HookOutcome> {
  try {
    if (event === "stop") {
      return await stop(payload, run);
    }
    const call = toolCallOf(payload);
    if (event === "pre-shell") {
      return call.command !== undefined && isShellTool(call) ? preShell(call.command) : OK;
    }
    if (call.paths.length === 0 || !isEditTool(call)) {
      return OK;
    }
    return event === "pre-edit" ? await preEdit(call.paths, run) : await postEdit(call.paths, run);
  } catch (error) {
    // Outside a workspace, or snagentic itself failing: never stop the agent's work over it.
    return {
      exitCode: 0,
      stdout: "",
      stderr: `snagentic hook skipped: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}
