import { afterEach, describe, expect, it } from "bun:test";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { runGitOrThrow } from "../../src/adapters/git/run-git";
import { toYaml } from "../../src/adapters/yaml/own-style";
import { runCli } from "../../src/cli/run-cli";
import { runClaudeHook } from "../../src/hooks/claude-hooks";
import { USE_CASES } from "../../src/registry/registry";
import { captureIo } from "../support/fakes";
import { instanceWorkspace } from "../support/instance-workspace";

const finding = (severity: string) => ({
  ruleId: "SN-SEC-001",
  severity,
  path: "global/x.script.js",
  line: 2,
  message: "eval() executes arbitrary strings as code",
  remediation: "Call the function directly.",
});
const edit = { tool_input: { file_path: "/w/instances/pdi/metadata/global/x.script.js" } };

describe("Claude Code hooks", () => {
  it("blocks an edit to a protected file before it happens, with the reason", async () => {
    const outcome = await runClaudeHook("pre-edit", edit, async (name, input) => {
      expect([name, input]).toEqual([
        "check",
        { paths: [edit.tool_input.file_path], edited: false },
      ]);
      return {
        protected: [{ path: "x", reason: "child rows are read-only" }],
        findings: [],
        passed: false,
      };
    });
    expect(outcome).toEqual({
      exitCode: 2,
      stdout: "",
      stderr: "snagentic: do not edit this file. x: child rows are read-only",
    });
    expect(
      await runClaudeHook("pre-edit", edit, async () => ({ protected: [], findings: [] })),
    ).toMatchObject({ exitCode: 0 });
  });

  it("feeds blocking findings back after an edit, and other findings as context", async () => {
    const blocked = await runClaudeHook("post-edit", edit, async () => ({
      findings: [finding("block")],
    }));
    expect(blocked.exitCode).toBe(2);
    expect(blocked.stderr).toContain(
      "block SN-SEC-001 global/x.script.js:2: eval() executes arbitrary strings as code Fix: Call the function directly.",
    );
    const warned = await runClaudeHook("post-edit", edit, async () => ({
      findings: [finding("warn")],
    }));
    expect(warned.exitCode).toBe(0);
    expect(JSON.parse(warned.stdout).hookSpecificOutput).toMatchObject({
      hookEventName: "PostToolUse",
    });
    expect(await runClaudeHook("post-edit", edit, async () => ({ findings: [] }))).toEqual({
      exitCode: 0,
      stdout: "",
      stderr: "",
    });
  });

  it("keeps the agent working while validate blocks, but only once per stop", async () => {
    const run = async () => ({ findings: [finding("block")] });
    const outcome = await runClaudeHook("stop", {}, run);
    expect(JSON.parse(outcome.stdout)).toMatchObject({
      decision: "block",
      reason: expect.stringContaining("SN-SEC-001"),
    });
    expect(await runClaudeHook("stop", { stop_hook_active: true }, run)).toEqual({
      exitCode: 0,
      stdout: "",
      stderr: "",
    });
    expect(
      await runClaudeHook("stop", {}, async () => ({ findings: [finding("warn")] })),
    ).toMatchObject({ stdout: "" });
  });

  it("never stops the agent over its own failure, or an event without a file", async () => {
    const failed = await runClaudeHook("post-edit", edit, async () => {
      throw new Error("no workspace here");
    });
    expect(failed).toEqual({
      exitCode: 0,
      stdout: "",
      stderr: "snagentic hook skipped: no workspace here",
    });
    expect(await runClaudeHook("post-edit", {}, async () => ({}))).toEqual({
      exitCode: 0,
      stdout: "",
      stderr: "",
    });
  });
});

describe("snagentic hook claude", () => {
  const cleanups: (() => Promise<void>)[] = [];
  afterEach(async () => {
    await Promise.all(cleanups.splice(0).map((cleanup) => cleanup()));
  });

  it("checks the edited file in a real workspace and tells the host to show the problem", async () => {
    const ws = await instanceWorkspace({});
    cleanups.push(ws.cleanup);
    const base = join(
      ws.root,
      "instances/pdi/metadata/global/sys_script_include/util--0123456789abcdef0123456789abcdef",
    );
    await mkdir(join(base, ".."), { recursive: true });
    await writeFile(
      `${base}.yaml`,
      toYaml({
        _meta: {
          sys_class_name: "sys_script_include",
          sys_id: "0123456789abcdef0123456789abcdef",
          scope: "global",
        },
        name: "Util",
        description: "d",
      }),
    );
    await writeFile(`${base}.script.js`, "var Util = 1;\n");
    await runGitOrThrow(["add", "instances"], ws.root);
    await runGitOrThrow(
      ["-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "pull"],
      ws.root,
    );
    await writeFile(`${base}.script.js`, "var Util = 1;\neval(input);\n");
    const io = captureIo();
    const payload = JSON.stringify({ tool_input: { file_path: `${base}.script.js` } });
    const exitCode = await runCli(
      ["hook", "claude", "post-edit", "--workspace", ws.root],
      USE_CASES,
      ws.context,
      io,
      {
        version: "test",
        serveMcp: async () => {},
        readStdin: async () => payload,
      },
    );
    expect(exitCode).toBe(2);
    expect(io.err()).toContain("block SN-SEC-001");
  });
});
