import { afterEach, describe, expect, it } from "bun:test";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { runGitOrThrow } from "../../src/adapters/git/run-git";
import { toYaml } from "../../src/adapters/yaml/own-style";
import { runCli } from "../../src/cli/run-cli";
import { runClaudeHook } from "../../src/hooks/claude-hooks";
import { USE_CASES } from "../../src/registry/registry";
import { captureIo } from "../support/fakes";
import { instanceWorkspace } from "../support/instance-workspace";

const finding = (severity: string) => ({
  ruleId: "SN-SEC-001",
  severity,
  path: "global/x.script.js",
  line: 2,
  message: "eval() executes arbitrary strings as code",
  remediation: "Call the function directly.",
});
const edit = { tool_input: { file_path: "/w/instances/pdi/metadata/global/x.script.js" } };

describe("Claude Code hooks", () => {
  it("blocks an edit to a protected file before it happens, with the reason", async () => {
    const outcome = await runClaudeHook("pre-edit", edit, async (name, input) => {
      expect([name, input]).toEqual([
        "check",
        { paths: [edit.tool_input.file_path], edited: false },
      ]);
      return {
        protected: [{ path: "x", reason: "child rows are read-only" }],
        findings: [],
        passed: false,
      };
    });
    expect(outcome).toEqual({
      exitCode: 2,
      stdout: "",
      stderr: "snagentic: do not edit this file. x: child rows are read-only",
    });
    expect(
      await runClaudeHook("pre-edit", edit, async () => ({ protected: [], findings: [] })),
    ).toMatchObject({ exitCode: 0 });
  });

  it("feeds blocking findings back after an edit, and other findings as context", async () => {
    const blocked = await runClaudeHook("post-edit", edit, async () => ({
      findings: [finding("block")],
    }));
    expect(blocked.exitCode).toBe(2);
    expect(blocked.stderr).toContain(
      "block SN-SEC-001 global/x.script.js:2: eval() executes arbitrary strings as code Fix: Call the function directly.",
    );
    const warned = await runClaudeHook("post-edit", edit, async () => ({
      findings: [finding("warn")],
    }));
    expect(warned.exitCode).toBe(0);
    expect(JSON.parse(warned.stdout).hookSpecificOutput).toMatchObject({
      hookEventName: "PostToolUse",
    });
    expect(await runClaudeHook("post-edit", edit, async () => ({ findings: [] }))).toEqual({
      exitCode: 0,
      stdout: "",
      stderr: "",
    });
  });

  it("keeps the agent working while validate blocks, but only once per stop", async () => {
    const run = async () => ({ findings: [finding("block")] });
    const outcome = await runClaudeHook("stop", {}, run);
    expect(JSON.parse(outcome.stdout)).toMatchObject({
      decision: "block",
      reason: expect.stringContaining("SN-SEC-001"),
    });
    expect(await runClaudeHook("stop", { stop_hook_active: true }, run)).toEqual({
      exitCode: 0,
      stdout: "",
      stderr: "",
    });
    expect(
      await runClaudeHook("stop", {}, async () => ({ findings: [finding("warn")] })),
    ).toMatchObject({ stdout: "" });
  });

  it("never stops the agent over its own failure, or an event without a file", async () => {
    const failed = await runClaudeHook("post-edit", edit, async () => {
      throw new Error("no workspace here");
    });
    expect(failed).toEqual({
      exitCode: 0,
      stdout: "",
      stderr: "snagentic hook skipped: no workspace here",
    });
    expect(await runClaudeHook("post-edit", {}, async () => ({}))).toEqual({
      exitCode: 0,
      stdout: "",
      stderr: "",
    });
  });
});

describe("hooks under other hosts", () => {
  const checked = (paths: string[]) => async (name: string, input: Record<string, unknown>) => {
    expect(name).toBe("check");
    paths.push(...(Array.isArray(input["paths"]) ? input["paths"].map(String) : []));
    return { protected: [{ path: "x", reason: "read-only" }], findings: [] };
  };

  it("checks every file in a Copilot CLI apply_patch edit, resolved against the session folder", async () => {
    const paths: string[] = [];
    const outcome = await runClaudeHook(
      "pre-edit",
      {
        hook_event_name: "PreToolUse",
        cwd: "/w",
        tool_name: "Edit",
        tool_input:
          "*** Begin Patch\n*** Add File: snagentic.yaml\n+x\n*** Update File: /w/a.js\n*** Move to: .snagentic/b.js\n@@\n-a\n+b\n*** Delete File: c.yaml\n*** End Patch\n",
      },
      checked(paths),
    );
    expect(outcome.exitCode).toBe(2);
    expect(paths).toEqual(["/w/snagentic.yaml", "/w/a.js", "/w/.snagentic/b.js", "/w/c.yaml"]);
  });

  it("reads the edited path from path, filePath and camelCase toolArgs payloads", async () => {
    for (const payload of [
      { tool_name: "create", tool_input: { path: "/w/snagentic.yaml" } },
      { tool_name: "editFiles", tool_input: { filePath: "/w/snagentic.yaml" } },
      { toolName: "edit", toolArgs: JSON.stringify({ path: "/w/snagentic.yaml" }) },
    ]) {
      const paths: string[] = [];
      expect((await runClaudeHook("pre-edit", payload, checked(paths))).exitCode).toBe(2);
      expect(paths).toEqual(["/w/snagentic.yaml"]);
    }
  });

  it("leaves reads alone when a host runs the edit hook for every tool", async () => {
    const outcome = await runClaudeHook(
      "pre-edit",
      { tool_name: "Read", tool_input: { file_path: "/w/snagentic.yaml" } },
      async () => {
        throw new Error("must not check a read");
      },
    );
    expect(outcome).toEqual({ exitCode: 0, stdout: "", stderr: "" });
  });

  it("gives Copilot the post-edit context at the top level as well", async () => {
    const outcome = await runClaudeHook("post-edit", edit, async () => ({
      findings: [finding("warn")],
    }));
    const output = JSON.parse(outcome.stdout);
    expect(output.additionalContext).toBe(output.hookSpecificOutput.additionalContext);
  });
});

describe("pre-shell hook", () => {
  const shell = (command: string, tool_name = "Bash") => ({ tool_name, tool_input: { command } });
  const never = async (): Promise<Record<string, unknown>> => {
    throw new Error("a shell hook needs no use case");
  };

  it("refuses commands that bypass snagentic or skip the git hooks", async () => {
    for (const command of [
      "curl -u admin https://dev1.service-now.com/api/now/table/sys_script",
      "cd x && wget https://example.com",
      "git commit --no-verify -m wip",
      "git commit -anm wip",
      "git -c core.hooksPath=/dev/null push",
      "python3 -c 'import requests; requests.get(\"https://dev1.service-now.com\")'",
      "env FOO=1 curl https://example.com",
    ]) {
      const outcome = await runClaudeHook("pre-shell", shell(command), never);
      expect([command, outcome.exitCode]).toEqual([command, 2]);
      expect(outcome.stderr).toStartWith("snagentic:");
    }
  });

  it("lets ordinary commands and non-shell tools through", async () => {
    for (const payload of [
      shell("bun test"),
      shell("git commit -m 'curly braces'"),
      shell("snagentic pull --instance pdi"),
      shell("curl https://example.com", "Read"),
      {},
    ]) {
      expect(await runClaudeHook("pre-shell", payload, never)).toEqual({
        exitCode: 0,
        stdout: "",
        stderr: "",
      });
    }
  });
});

describe("snagentic hook claude", () => {
  const cleanups: (() => Promise<void>)[] = [];
  afterEach(async () => {
    await Promise.all(cleanups.splice(0).map((cleanup) => cleanup()));
  });

  it("checks the edited file in a real workspace and tells the host to show the problem", async () => {
    const ws = await instanceWorkspace({});
    cleanups.push(ws.cleanup);
    const base = join(
      ws.root,
      "instances/pdi/metadata/global/sys_script_include/util--0123456789abcdef0123456789abcdef",
    );
    await mkdir(join(base, ".."), { recursive: true });
    await writeFile(
      `${base}.yaml`,
      toYaml({
        _meta: {
          sys_class_name: "sys_script_include",
          sys_id: "0123456789abcdef0123456789abcdef",
          scope: "global",
        },
        name: "Util",
        description: "d",
      }),
    );
    await writeFile(`${base}.script.js`, "var Util = 1;\n");
    await runGitOrThrow(["add", "instances"], ws.root);
    await runGitOrThrow(
      ["-c", "user.name=t", "-c", "user.email=t@t", "commit", "-qm", "pull"],
      ws.root,
    );
    await writeFile(`${base}.script.js`, "var Util = 1;\neval(input);\n");
    const io = captureIo();
    const payload = JSON.stringify({ tool_input: { file_path: `${base}.script.js` } });
    const exitCode = await runCli(
      ["hook", "claude", "post-edit", "--workspace", ws.root],
      USE_CASES,
      ws.context,
      io,
      {
        version: "test",
        serveMcp: async () => {},
        readStdin: async () => payload,
      },
    );
    expect(exitCode).toBe(2);
    expect(io.err()).toContain("block SN-SEC-001");
  });
});
